add --merger-delete-threads
streamingfast/firehose-core pull request #42
Opened 2024-03-21 15:35 UTC by fschoell

2024-03-21 23:16 UTC, maoueh requested changes
The rest is all good

2024-03-21 23:16 UTC, maoueh commented on CHANGELOG.md
> +* Added `--merger-delete-threads` to customize the number of threads the merger will use to delete files.
Can you add a note that this is particularly useful for those on Ceph storage provider.

2024-03-21 23:16 UTC, maoueh commented on CHANGELOG.md
> +* Added `--merger-delete-threads` to customize the number of threads the merger will use to delete files.
And how manu threads you use there

2024-03-22 08:49 UTC, fschoell commented on CHANGELOG.md
> +* Added `--merger-delete-threads` to customize the number of threads the merger will use to delete files.
added some context

2024-03-22 16:04 UTC, maoueh approved these changes

2024-03-22 16:04 UTC, merged