add reader-node-firehose
streamingfast/firehose-core pull request #63
Opened 2024-09-04 15:20 UTC by fschoell

This adds a new reader-node app that reads blocks from another Firehose endpoint. This allows indexers to bootstrap a Firehose/Substreams stack without having to set up an instrumented blockchain node initially.

2024-09-06 14:04 UTC, maoueh requested changes

2024-09-06 14:04 UTC, maoueh commented on node-manager/app/firehose_reader/app.go
> +	a.OnTerminating(mindreaderLogPlugin.Shutdown)
Ideally, we would avoid completely the mindreader plugin, there is overall little reason to use outside avoiding re-implementing two things:
- Save received one block to one-blocks-store
- Emit block on block stream server

I understand it make the implementation easier. But I have the overall feeling that it will make a much simpler implementation since we will move away from the node-manager.

We should also move to something else than `node-manager` as the top-level package.

2024-09-06 14:04 UTC, maoueh commented on node-manager/app/firehose_reader/console_reader.go
> +	}
How do we deal with connection errors?

2024-09-06 14:04 UTC, maoueh commented on node-manager/app/firehose_reader/reader_stats.go
> +		ticker := time.NewTicker(logEach)
ticker has a `Stop()` let's defer stop it.

2024-09-06 14:04 UTC, maoueh commented on node-manager/app/firehose_reader/reader_stats.go
> +		ticker := time.NewTicker(logEach)
`blockRate` too has a `Stop` method. Could go in `StopPeriodicLogToZap()` too.

2024-09-09 08:57 UTC, fschoell commented on node-manager/app/firehose_reader/app.go
> +	a.OnTerminating(mindreaderLogPlugin.Shutdown)
Sounds good. Should I move it into its own top-level package or is there another package to include it in?

2024-09-09 13:26 UTC, sduchesneau commented
1. @fschoell  let's add this new app to `appsNotRunningByDefault` in cmd/apps/start.go

2. I agree with @maoueh that using the consoleReader feels very hackish and I'd much prefer copying the bits that you need to reimplement something more slim.

With these fixed, I think we could merge it.

2024-12-16 18:16 UTC, maoueh commented on node-manager/app/firehose_reader/app.go
> +	a.OnTerminating(mindreaderLogPlugin.Shutdown)
A new top-level `reader-node-firehose` seems good, the `package <name>` could be shorter if needed.

2024-12-16 18:27 UTC, matthewdarwin commented
Fred will continue on this in the new year.

2024-12-16 19:49 UTC, maoueh commented
@matthewdarwin I reviewed the SQL PRs too. If there is something I missed, let me know.

2025-04-30 14:40 UTC, maoueh commented
Merged on the side.

2025-04-30 14:40 UTC, closed without merging